//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About / Change language ähnelt.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download latest branch ähnelt.
        /// </summary>
        internal static string bdllb {
            get {
                return ResourceManager.GetString("bdllb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure installation directory ähnelt.
        /// </summary>
        internal static string config_installdir {
            get {
                return ResourceManager.GetString("config_installdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Danish: ähnelt.
        /// </summary>
        internal static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German: ähnelt.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory does not exist! ähnelt.
        /// </summary>
        internal static string dirnotfound {
            get {
                return ResourceManager.GetString("dirnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please check your choosen directory! ähnelt.
        /// </summary>
        internal static string dirnotfoundmessage {
            get {
                return ResourceManager.GetString("dirnotfoundmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The download has been finished and is ready for installation. ähnelt.
        /// </summary>
        internal static string dl_finished {
            get {
                return ResourceManager.GetString("dl_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download finished ähnelt.
        /// </summary>
        internal static string dl_finished_title {
            get {
                return ResourceManager.GetString("dl_finished_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download older branch ähnelt.
        /// </summary>
        internal static string dl_ob {
            get {
                return ResourceManager.GetString("dl_ob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A download has been started! ähnelt.
        /// </summary>
        internal static string dl_started {
            get {
                return ResourceManager.GetString("dl_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download started! ähnelt.
        /// </summary>
        internal static string dl_started_title {
            get {
                return ResourceManager.GetString("dl_started_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download latest master ähnelt.
        /// </summary>
        internal static string dlmaster {
            get {
                return ResourceManager.GetString("dlmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download latest testing build ähnelt.
        /// </summary>
        internal static string dltesting {
            get {
                return ResourceManager.GetString("dltesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit bootdtrap.ini ähnelt.
        /// </summary>
        internal static string edit_bs_ini {
            get {
                return ResourceManager.GetString("edit_bs_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English: ähnelt.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spanish: ähnelt.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file has sucsessfully been saved! ähnelt.
        /// </summary>
        internal static string filesave {
            get {
                return ResourceManager.GetString("filesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die French: ähnelt.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go back? ähnelt.
        /// </summary>
        internal static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It might help to run this program as administrator. ähnelt.
        /// </summary>
        internal static string help_runasadmin {
            get {
                return ResourceManager.GetString("help_runasadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation could not be startet due to the following error: ähnelt.
        /// </summary>
        internal static string installerror {
            get {
                return ResourceManager.GetString("installerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation could not be started! ähnelt.
        /// </summary>
        internal static string installnostart {
            get {
                return ResourceManager.GetString("installnostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The language setting will apply at the next startup! ähnelt.
        /// </summary>
        internal static string language_change_success {
            get {
                return ResourceManager.GetString("language_change_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No install directory choosen! ähnelt.
        /// </summary>
        internal static string no_installdir {
            get {
                return ResourceManager.GetString("no_installdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normally you should choose a LibreOffice Installation file! Continue? ähnelt.
        /// </summary>
        internal static string no_installfile {
            get {
                return ResourceManager.GetString("no_installfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open bootstrap.ini ähnelt.
        /// </summary>
        internal static string open_bootstrap_ini {
            get {
                return ResourceManager.GetString("open_bootstrap_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open bootstrap.ini ähnelt.
        /// </summary>
        internal static string open_bootstrap_title {
            get {
                return ResourceManager.GetString("open_bootstrap_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open LibreOffice help installer ähnelt.
        /// </summary>
        internal static string open_help {
            get {
                return ResourceManager.GetString("open_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open LibreOffice installer ähnelt.
        /// </summary>
        internal static string open_installer {
            get {
                return ResourceManager.GetString("open_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programmer: ähnelt.
        /// </summary>
        internal static string programmer {
            get {
                return ResourceManager.GetString("programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress: ähnelt.
        /// </summary>
        internal static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save bootstrap.ini ähnelt.
        /// </summary>
        internal static string save_bootstrap_ini {
            get {
                return ResourceManager.GetString("save_bootstrap_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security Issue ähnelt.
        /// </summary>
        internal static string si {
            get {
                return ResourceManager.GetString("si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You do not have the right to write into this folder. ähnelt.
        /// </summary>
        internal static string si_message {
            get {
                return ResourceManager.GetString("si_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slovenian: ähnelt.
        /// </summary>
        internal static string sl {
            get {
                return ResourceManager.GetString("sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occoured! Message: ähnelt.
        /// </summary>
        internal static string standarderror {
            get {
                return ResourceManager.GetString("standarderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start installation ähnelt.
        /// </summary>
        internal static string start_install {
            get {
                return ResourceManager.GetString("start_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should the file be downloaded? ähnelt.
        /// </summary>
        internal static string startdl {
            get {
                return ResourceManager.GetString("startdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should a subfolder be created automatically? Name of the subfolder: ähnelt.
        /// </summary>
        internal static string subfolder_do {
            get {
                return ResourceManager.GetString("subfolder_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success! ähnelt.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File saved ähnelt.
        /// </summary>
        internal static string title_filesave {
            get {
                return ResourceManager.GetString("title_filesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --- Translations --- ähnelt.
        /// </summary>
        internal static string translations {
            get {
                return ResourceManager.GetString("translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translator: ähnelt.
        /// </summary>
        internal static string translator {
            get {
                return ResourceManager.GetString("translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You may use the following instead of the line starting with “UserInstallation=” from the text field above in order to not override your existing user profile. ähnelt.
        /// </summary>
        internal static string tt_bootstrap {
            get {
                return ResourceManager.GetString("tt_bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest build of latest branch. ähnelt.
        /// </summary>
        internal static string tt_lb {
            get {
                return ResourceManager.GetString("tt_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest daily build. ähnelt.
        /// </summary>
        internal static string tt_m {
            get {
                return ResourceManager.GetString("tt_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest build of older branch. ähnelt.
        /// </summary>
        internal static string tt_ob {
            get {
                return ResourceManager.GetString("tt_ob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest testing build. ähnelt.
        /// </summary>
        internal static string tt_tb {
            get {
                return ResourceManager.GetString("tt_tb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change language: ähnelt.
        /// </summary>
        internal static string update_lang {
            get {
                return ResourceManager.GetString("update_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should %version really be downloaded? ähnelt.
        /// </summary>
        internal static string versiondl {
            get {
                return ResourceManager.GetString("versiondl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning! ähnelt.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose installation directory ähnelt.
        /// </summary>
        internal static string where_to_install {
            get {
                return ResourceManager.GetString("where_to_install", resourceCulture);
            }
        }
    }
}
